version: '2.4'
services:
    mysql:
        image: mysql:5.7.31
        restart: always
        ports:
            - "${PORT_DOCKER_MYSQL}:3306"
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - "./database:/var/lib/mysql/"
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
            timeout: 20s
            retries: 10

    wordpress:
        image: wp-local-build:latest
        build: build/wordpress
        restart: always
        ports:
            - "${PORT_DOCKER_WORDPRESS}:443"
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_CONFIG_EXTRA: |
                define('AUTOMATIC_UPDATER_DISABLED', true);
        volumes:
            - "./themes:/var/www/html/wp-content/themes/"
            - "./plugins:/var/www/html/wp-content/plugins"
            - "./uploads:/var/www/html/wp-content/uploads"
            - "./ssl:/var/www/ssl"
            - "./logs:/var/www/logs"
            - "./build/apache2/wordpress-in-docker.000-default.conf:/etc/apache2/sites-available/000-default.conf"
            - "./build/wordpress/overrides.php.ini:/usr/local/etc/php/conf.d/overrides.php.ini"
            - "./build/wordpress/startup.sh:/startup.sh"
        entrypoint: "/startup.sh"
        depends_on:
            mysql:
                condition: service_healthy

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "${PORT_DOCKER_PHPMYADMIN}:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - "./ssl:/var/www/ssl"
            - "./logs:/var/www/logs"
            - "./build/apache2/phpmyadmin-in-docker.000-default.conf:/etc/apache2/sites-available/000-default.conf"
        depends_on:
            mysql:
                condition: service_healthy
